/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 MIDI Product Piano - R1.glb -t 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { UserInputKeys } from "@/store/input";
import AnimatedPianoKey from "../Ryoturia/AnimatedPianoKey";

type ModelKeyMap = {
  c: boolean;
  d: boolean;
  e: boolean;
  f: boolean;
  g: boolean;
  a: boolean;
  b: boolean;
  csharp: boolean;
  dsharp: boolean;
  fsharp: boolean;
  gsharp: boolean;
  asharp: boolean;
};

type Props = JSX.IntrinsicElements["group"] & {
  piano: ModelKeyMap;
  setInput: (key: UserInputKeys, input: boolean) => void;
};

type GLTFResult = GLTF & {
  nodes: {
    Cube003: THREE.Mesh;
    Cube003_1: THREE.Mesh;
    ["BlackKeyG#"]: THREE.Mesh;
    ["BlackKeyC#"]: THREE.Mesh;
    WhiteKeySlimC: THREE.Mesh;
    WhiteKeySlimD: THREE.Mesh;
    WhiteKeySlimE: THREE.Mesh;
    WhiteKeySlimF: THREE.Mesh;
    WhiteKeySlimG: THREE.Mesh;
    WhiteKeySlimA: THREE.Mesh;
    WhiteKeySlimB: THREE.Mesh;
    ["BlackKeyD#"]: THREE.Mesh;
    ["BlackKeyF#"]: THREE.Mesh;
    ["BlackKeyA#"]: THREE.Mesh;
  };
  materials: {
    Brushed_Aluminum_shkaaafc: THREE.MeshStandardMaterial;
    Screen: THREE.MeshStandardMaterial;
    ["PianoKey.Black"]: THREE.MeshStandardMaterial;
  };
};

export default function ProductPianoModel({
  piano,
  setInput,
  ...props
}: Props) {
  const { nodes, materials } = useGLTF(
    "/models/product-piano/MIDI Product Piano - R1.gltf"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group position={[-0.682, 1.109, -2.962]}>
        <mesh
          geometry={nodes.Cube003.geometry}
          material={materials.Brushed_Aluminum_shkaaafc}
        />
        <mesh geometry={nodes.Cube003_1.geometry} material={materials.Screen} />
      </group>

      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        black
        geometry={nodes["BlackKeyG#"].geometry}
        material={materials["PianoKey.Black"].clone()}
        position={[4.323, 0.986, -5.417]}
        pressed={piano.gsharp}
        note="G#4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        black
        geometry={nodes["BlackKeyC#"].geometry}
        material={materials["PianoKey.Black"]}
        position={[-0.031, 0.986, -5.417]}
        pressed={piano.csharp}
        note="C#4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        geometry={nodes.WhiteKeySlimC.geometry}
        material={materials.Brushed_Aluminum_shkaaafc}
        position={[-0.496, 0.813, -5.439]}
        pressed={piano.c}
        note="C4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        geometry={nodes.WhiteKeySlimD.geometry}
        material={materials.Brushed_Aluminum_shkaaafc}
        position={[-0.496, 0.813, -5.439]}
        pressed={piano.d}
        note="D4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        geometry={nodes.WhiteKeySlimE.geometry}
        material={materials.Brushed_Aluminum_shkaaafc}
        position={[-0.496, 0.813, -5.439]}
        pressed={piano.e}
        note="E4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        geometry={nodes.WhiteKeySlimF.geometry}
        material={materials.Brushed_Aluminum_shkaaafc}
        position={[-0.496, 0.813, -5.439]}
        pressed={piano.f}
        note="F4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        geometry={nodes.WhiteKeySlimG.geometry}
        material={materials.Brushed_Aluminum_shkaaafc}
        position={[-0.496, 0.813, -5.439]}
        pressed={piano.g}
        note="G4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        geometry={nodes.WhiteKeySlimA.geometry}
        material={materials.Brushed_Aluminum_shkaaafc}
        position={[-0.496, 0.813, -5.439]}
        pressed={piano.a}
        note="A4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        geometry={nodes.WhiteKeySlimB.geometry}
        material={materials.Brushed_Aluminum_shkaaafc}
        position={[-0.496, 0.813, -5.439]}
        pressed={piano.b}
        note="B4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        black
        geometry={nodes["BlackKeyD#"].geometry}
        material={materials["PianoKey.Black"]}
        position={[-0.031, 0.986, -5.417]}
        pressed={piano.dsharp}
        note="D#4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        black
        geometry={nodes["BlackKeyF#"].geometry}
        material={materials["PianoKey.Black"]}
        position={[1.044, 0.986, -5.417]}
        pressed={piano.fsharp}
        note="F#4"
        setInput={setInput}
      />
      <AnimatedPianoKey
        whiteKeyRotation={0.013155}
        black
        geometry={nodes["BlackKeyA#"].geometry}
        material={materials["PianoKey.Black"]}
        position={[4.323, 0.986, -5.417]}
        pressed={piano.asharp}
        note="A#4"
        setInput={setInput}
      />
    </group>
  );
}

useGLTF.preload("/models/product-piano/MIDI Product Piano - R1.gltf");
